# Generated by Django 2.2.13 on 2021-05-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210526_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spri', to='myapp.Team'),
        ),
    ]
