# Generated by Django 2.2.13 on 2021-05-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210526_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='product_backlog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logStor', to='myapp.ProductBacklog'),
        ),
    ]
